[[permission]]
identifier = "allow-net"
description = "Allows controlling the embedded tsnet node and storing the Headscale pre-auth key."
commands.allow = [
  "net_start",
  "net_stop",
  "net_status",
  "net_load_auth_key",
  "net_save_auth_key"
]
