//! iOS Network Extension helpers for dadiMesh.
//!
//! The Packet Tunnel Provider lives under `dadimesh-extension/` and is linked
//! into the Xcode project generated by `tauri ios init`. These Rust helpers
//! write App Group credentials and drive NETunnelProviderManager via
//! Objective-C bridging when building for iOS.

#![allow(dead_code)]

use crate::net::Credentials;

#[cfg(not(target_os = "ios"))]
pub fn ensure_vpn_configuration() -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
pub fn start_tunnel(_port: u16) -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
pub fn stop_tunnel() -> Result<(), String> {
    Ok(())
}

#[cfg(not(target_os = "ios"))]
pub fn write_shared_credentials(_credentials: &Credentials) -> Result<(), String> {
    Ok(())
}

#[cfg(target_os = "ios")]
mod ios {
    use super::*;
    use std::ffi::CString;
    use std::os::raw::{c_char, c_int};

    // Provided by dadimesh-extension/DadiMeshBridge.m when linked into the iOS app.
    extern "C" {
        fn dadimesh_vpn_ensure() -> c_int;
        fn dadimesh_vpn_start(proxy_port: c_int) -> c_int;
        fn dadimesh_vpn_stop() -> c_int;
        fn dadimesh_vpn_write_credentials(
            control_url: *const c_char,
            auth_key: *const c_char,
            node_name: *const c_char,
        ) -> c_int;
    }

    pub fn ensure_vpn_configuration() -> Result<(), String> {
        let code = unsafe { dadimesh_vpn_ensure() };
        if code != 0 {
            return Err(format!("dadimesh vpn ensure failed ({code})"));
        }
        Ok(())
    }

    pub fn start_tunnel(port: u16) -> Result<(), String> {
        let code = unsafe { dadimesh_vpn_start(port as c_int) };
        if code != 0 {
            return Err(format!("dadimesh vpn start failed ({code})"));
        }
        Ok(())
    }

    pub fn stop_tunnel() -> Result<(), String> {
        let code = unsafe { dadimesh_vpn_stop() };
        if code != 0 {
            return Err(format!("dadimesh vpn stop failed ({code})"));
        }
        Ok(())
    }

    pub fn write_shared_credentials(credentials: &Credentials) -> Result<(), String> {
        let control = CString::new(credentials.control_url.as_str()).map_err(|e| e.to_string())?;
        let key = CString::new(credentials.auth_key.as_str()).map_err(|e| e.to_string())?;
        let host = CString::new(credentials.node_name.as_str()).map_err(|e| e.to_string())?;
        let code = unsafe {
            dadimesh_vpn_write_credentials(control.as_ptr(), key.as_ptr(), host.as_ptr())
        };
        if code != 0 {
            return Err(format!("dadimesh vpn write credentials failed ({code})"));
        }
        Ok(())
    }
}

#[cfg(target_os = "ios")]
pub use ios::*;
